#Global configuration
spring.application.name=safetyNetAlerts

#Log level configuration
#logging.level.root=ERROR
logging.level.springframework.boot.web.embedded.tomcat=INFO
logging.level.com.openclassrooms=INFO
logging.level.com.openclassrooms.safetyNetAlerts.service=INFO
#logging.level.com.openclassrooms.safetyNetAlerts.service=DEBUG

# swagger-ui custom path
springdoc.api-docs.path=api-docs
springdoc.swagger-ui.path=/swagger-ui.html